# image:
#   tag: 4.4.4-debian-10-r27 # Choose mongodb tag version
auth:
  existingSecret: bookinfo-dev-ratings-mongodb-secret # Password; Reference to bookinfo-dev-ratings-mongodb-secret.metadata.name
  username: ratings-dev # Database username
  database: ratings-dev # Database name
persistence:
  enabled: false
initdbScriptsConfigMap: bookinfo-dev-ratings-mongodb-initdb # Migration file