apiVersion: v1
kind: Secret
metadata:
  name: bookinfo-uat-ratings-mongodb-secret
  namespace: bookinfo-uat
type: Opaque
data:
  mongodb-root-password: "uatcmF0aW5ncy1kZXYtcm9vdA=="
  mongodb-password: "uatcmF0aW5ncy1kZXY="
