apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }} # Application-ENV-Service
  namespace: {{ .Values.ratings.namespace }}
spec:
  type: {{ .Values.ingress.serviceType }} # wait for invoked by ingress controller
  ports:
    - port: {{ .Values.ratings.port }} # service details, productpage, ratings, reviews use this port
  selector:
    app: {{ .Release.Name }} # must same as deployment.lables.app
