apiVersion: v1
kind: Pod                   # ชนิิดของ resource
metadata:
  name: busybox
  namespace: bookinfo-dev
spec:                       # Spec ของ Pod
  containers:
  - name: busybox
    image: busybox          # Pod for debuging
    command:
    - sleep
    - "3600"